export const FILTER_DATA_REQUEST = "FILTER_DATA_REQUEST";
export const FILTER_DATA_SUCCESS = "FILTER_DATA_SUCCESS";
export const FILTER_DATA_FAIL = "FILTER_DATA_FAIL";

export const BUILDING_DATA_REQUEST = "BUILDING_DATA_REQUEST";
export const BUILDING_DATA_SUCCESS = "BUILDING_DATA_SUCCESS";
export const BUILDING_DATA_FAIL = "BUILDING_DATA_FAIL";
